spring.application.name=_10_MOUK_MAKARA_PVH_SPRING_Homework003
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticketing
spring.datasource.username=postgres
spring.datasource.password=Admin
